/* 
* PROJECT EULER PROBLEM 2
* Even Fibonacci Numbers
* Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
* 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
* By considering the terms in the Fibonacci sequence that do not exceed the nth term, find the sum of the even-valued terms.
*/

function fiboEvenSum(n) {
  let fiboArr = [1,2]
  let result = 0; 
  
  while (n>fiboArr[fiboArr.length-1]){
    fiboArr.push(fiboArr[fiboArr.length-1]+fiboArr[fiboArr.length-2])
  }
  
  for (let i=0; i < fiboArr.length; i++){
    if (fiboArr[i]%2 == 0 && fiboArr[i]<=n){
      result = result + fiboArr[i]
    }
  }
  return result
}
